// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20231128014853_Criando-Seed")]
    partial class CriandoSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CatagoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CatagoryName = "Camisa",
                            Description = "Uma linda camisa do jurassipark preta com vermelho",
                            ImageUrl = "Test",
                            Name = "Camisa JurassyPark",
                            Price = 69.799999999999997
                        },
                        new
                        {
                            Id = 3L,
                            CatagoryName = "Capacete",
                            Description = "Uma capacete do dart veider pequeno da cor preta",
                            ImageUrl = "Test",
                            Name = "Capacete dart veider",
                            Price = 169.80000000000001
                        },
                        new
                        {
                            Id = 4L,
                            CatagoryName = "Boneco",
                            Description = "Um boneco de 1.10 branco do tropper storm",
                            ImageUrl = "Test",
                            Name = "Boneco storm",
                            Price = 269.80000000000001
                        },
                        new
                        {
                            Id = 5L,
                            CatagoryName = "Camisa",
                            Description = "Uma linda camisa gamer preta",
                            ImageUrl = "Test",
                            Name = "Camisa gamer",
                            Price = 69.799999999999997
                        },
                        new
                        {
                            Id = 6L,
                            CatagoryName = "Camisa",
                            Description = "Uma linda camisa da spacex branca com a manga azul",
                            ImageUrl = "Test",
                            Name = "Camisa spacex",
                            Price = 69.799999999999997
                        },
                        new
                        {
                            Id = 7L,
                            CatagoryName = "Camisa",
                            Description = "Uma linda camisa da coffer amarelada",
                            ImageUrl = "Test",
                            Name = "Camisa coffer",
                            Price = 69.799999999999997
                        },
                        new
                        {
                            Id = 8L,
                            CatagoryName = "Moleton",
                            Description = "Um lindo moletom preto da serie cobra kay",
                            ImageUrl = "Test",
                            Name = "Moletom cobra kay",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 9L,
                            CatagoryName = "Camisa",
                            Description = "Uma linda camisa do jurassipark preta com vermelho",
                            ImageUrl = "Test",
                            Name = "filme stall tack",
                            Price = 69.799999999999997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
